language: d
sudo: false
d:
  - dmd
  - ldc
  - gdc

script:
  - dub test -b unittest-cov --compiler=${DC}
  - dub run --config=bc --compiler=${DC}

after_success:
  - bash <(curl -s https://codecov.io/bash)

