language: d
sudo: false
d:
  - dmd
  - ldc
#  - gdc # not yet supported.

script:
  - dub test -b unittest-cov --compiler=${DC}
  - dub run --config=bc --build=unittest --compiler=${DC}

after_success:
  - bash <(curl -s https://codecov.io/bash)

